### ISSUE TITLE
HTTP Parking API does not allow HEAD requests

### ISSUE THREAD

**Issue by kasei** [CityofSantaMonica/Orchard.ParkingData#25]
Returns HTTP/1.1 405 Method Not Allowed.

**Comment by thekaveman** [comment]
Yes, it should. 

For the `/lots` endpoint I can return a header with the last update time of the data.

For the `/meters` endpoint I can return a header with the last update time of the *static* meter data.

Can you think of others that would be useful?

**Comment by kasei** [comment]
That would be nice, yeah. Honestly, I hadn't even gotten that far when I noticed this problem. I was mostly just poking around the API and ran across the problem when I was trying to see if gzip encoding was supported (it is, but it's currently not possible to know this with a HEAD request).

**Comment by thekaveman** [comment]
Now that we have a `/meters/events/latest` endpoint (see #35), sending a HEAD request there should return some useful headers, like the latest event's ordinal and event time.
