### ISSUE TITLE
Investigate geo-queries for events

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/Orchard.ParkingData#28]
e.g. get the last 3 days of events for a given block in the city

**Comment by thekaveman** [comment]
Here are some ideas we're thinking about for geo-querying. Comments and suggestions welcome:

## Radius from a point

e.g. *50 meters from a given lat/long position*

A simple API could look like 

    GET /meters/events/within/:radius/of/:lat,:long


## Geographic polygon

We would want to support arbitrary polygons - sections of a street, entire streets, neighborhoods, the entire city; but this becomes a little trickier since URLs have an upper-limit on length.

One idea is to provide a `POST` endpoint where the polygon (maybe as [Well-Known Text](http://en.wikipedia.org/wiki/Well-known_text)) is provided as the request body. This would allow for simpler representation of the polygon but would require a slightly more complicated request pipeline that isn't quite as RESTful (`POST` vs. simpler `GET`)

Another idea is to make use of Google's [Encoded Polyline Algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) to encode the points making up a polygon into string that is compatible with URLs. This would allow the API to remain `GET`-oriented, at the expense of a slightly more complicated parameter syntax.

**Comment by kamronbatman** [comment]
It would be great to have this!

**Comment by thekaveman** [comment]
@kevinsmgov any thoughts on the points (:laughing:) above regarding querying a geographic polygon...The tradeoff between a simpler query syntax using WKT, or a more complex but RESTful encoded polyline syntax?

**Comment by kevinsmgov** [comment]
As a rough estimate, WKT will use 20 characters per coordinate (at 5 digits of decimal precision) and Google's encoding will use 10 characters for the first point and then 3-5 for each additional point (depending on how far away the points are from each other - it's a series of deltas)

I'm not really sure what the use-case for a really complex polygon would be (I'd love to hear some example use-cases for them though) so we might want to wait for some feedback before we add support for anything super-complex.
