### ISSUE TITLE
CORS not working from localhost

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/Orchard.ParkingData#30]
@chrislkeller was trying to hit the `/lots` endpoint from javascript (AJAX) on localhost, and was getting a CORS error

**Comment by chrislkeller** [comment]
Console output was ```www.projects.chrislkeller.com/:1 XMLHttpRequest cannot load https://parking.api.smgov.net/lots. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.projects.chrislkeller.com' is therefore not allowed access.```

Here are the approaches I took...

```$.getJSON("https://parking.api.smgov.net/lots", app.accept_data);```

```
$.ajax({

    url: "https://parking.api.smgov.net/lots",

    type: "GET",

    crossDomain: true,

    contentType: "application/json",

    dataType: "json",

    headers: {
        Accept: "application/json; charset=utf-8",
        "Content-Type": "text/plain; charset=utf-8"
    },

    success: function(data){
        console.log(data)
    }

});
```

**Comment by thekaveman** [comment]
@chrislkeller I just pushed a fix (see #31) to the public API that should make CORS requests possible. 

Here's the code I used (from a localhost page)

```js
$.ajax({
    url: "https://parking.api.smgov.net/lots",
    type: "GET",
    dataType: "json",
    success: function(data) {
        console.log(data);
    },
    error: function(data) {
         console.log(data);
    }
}); 
```

Can you try it out and verify?

**Comment by chrislkeller** [comment]
@thekaveman: I can confirm its working on localhost... Nice & thanks.

```0: Object
available_spaces: 249
description: "Off of PCH"
last_update: "20150609T182800Z"
latitude: 34.023972
longitude: -118.512472
name: "Beach House Lot"
street_address: "445 Pacific Coast Hwy"
zip_code: 90401```

**Comment by thekaveman** [comment]
Awesome! Thanks for testing
