### ISSUE TITLE
Meter Events Calls Returning Empty Arrays

### ISSUE THREAD

**Issue by samjabrahams** [CityofSantaMonica/Orchard.ParkingData#33]
All calls to the /meters/events URI, other than the /lifetime functions, are returning empty arrays. This includes the "since" functionality, as well as /meters/{meter id}/events calls.

**Comment by samjabrahams** [comment]
It appears to have resolved. Not sure what happened, but the same calls are now returning events!

**Comment by samjabrahams** [comment]
Odd- events seem to periodically not be

**Comment by thekaveman** [comment]
From @samjabrahams email:

>  Throughout the day, the `/meters/events` route returns an empty array, though it seems kind of insane that not a single meter would emit an event within a minute at noonish in Santa Monica...Usually I see stoppage in data in the mornings - if you'd like, I can make a log of times it happens so that you can take a look.

Thanks for following up with this. I agree that it seems *totally unlikely* that there would not be even a single event in the span of a minute, during the middle of the day here. 

My guess at what is going on: although events are being generated constantly, they are not making it to the server fast enough (e.g. within the lifetime) to be available on the API. 

What I can do for now is increase the lifetime and see if that makes a difference. From your end, do some logging if you can and let me know if you see a pattern (e.g. is it happening at the same time every day?). I'm also in the process of setting up a (publicly available) historical record of every event that this API captures, which could be post-analyzed to see if there any obvious problems.

**Comment by samjabrahams** [comment]
For sure. The api is currently not throwing events (4:20 pm PST), so I was able to set up a logger on my server. It makes a GET request to the standard events route and makes an entry if it gets an empty response. It does this every 30 seconds (hopefully this isn't too frequently).I'll have it run for a week or so and we should hopefully have a bunch of data to look at.

**Comment by thekaveman** [comment]
Here are some recent records from the database:

EventTime|TranmissionTime|ReceivedTime
----------------------|--------------|---------------------
|2015-06-19 22:42:54|2015-06-19 23:48:05		|2015-06-19 23:48:11
|2015-06-19 22:42:44|2015-06-19 23:48:05			|2015-06-19 23:48:10
|2015-06-19 22:42:42|2015-06-19 23:48:05		|2015-06-19 23:48:10
|2015-06-19 22:42:46|2015-06-19 23:48:05		|2015-06-19 23:48:09
|2015-06-19 22:43:01|2015-06-19 23:48:05			|2015-06-19 23:48:09
|2015-06-19 22:42:41|2015-06-19 23:48:05		|2015-06-19 23:48:09
|2015-06-19 22:42:37|2015-06-19 23:48:05			|2015-06-19 23:48:08
|2015-06-19 22:42:41|2015-06-19 23:48:05			|2015-06-19 23:48:08

So events are not being transmitted until an hour or more after occurring. This is definitely a problem! I'll continue looking in to this...

**Comment by samjabrahams** [comment]
Interesting. Damn this slow Santa Monica electricity! Thanks for looking into this- I'll come up with a way to digest the data from my logs over the next few days. Let me know if there's anything else I can do to help out.

**Comment by ericchapman** [comment]
Hey guys.  Any update on this?  I am noticing the empty array for "/meters/events" as well.

My problem is I am using that to initialize my "last ordinal" so I can make periodic subsequent calls to get updates since "last ordinal".  The issue I am having is that when this returns an empty array, my ordinal initializes to 0 and my system asks the server for all of the events since "0".  BOOM!!!

Anyone know of a better way for me to get the current ordinal so I don't have to start from 0?  I am considering just grabbing the events from a random meter so I at least have something that is not 0.

**Comment by thekaveman** [comment]
@ericchapman @samjabrahams thanks for the continued feedback guys.

I just deployed a couple of new endpoints that should at least make it easier to keep your code in sync with the server. 

`/meters/events/latest` gets you the most recent event across all meters

`/meters/<meter_id>/events/latest` gets you the most recent event at a given meter.

I've been in touch with the meter vendor, and we're looking in to the root issue behind the delays. Stay tuned!

**Comment by ericchapman** [comment]
@thekaveman Thanks Kegan

**Comment by samjabrahams** [comment]
Great, thanks for the new route! @ericchapman, my solution was to reset my server's ordinal to null, start making calls to the /events route instead of the /events/since route, and reset my ordinal to the latest one once the server started giving events again.

@thekaveman - I've got a rough little log to look at some preliminary stats over the past few days. I'll keep logging and see if a pattern emerges. Let me know if you want a different format or the raw JSON log.

```
********** ~ JUNE ~ **********
19 | HOURS AFFECTED: 6
	16: 43 minutes gave no events
	17: 60 minutes gave no events
	18: 60 minutes gave no events
	19: 60 minutes gave no events
	20: 60 minutes gave no events
	21: 52 minutes gave no events
20 | HOURS AFFECTED: 1
	4: 10 minutes gave no events
21 | HOURS AFFECTED: 4
	4: 19 minutes gave no events
	5: 5 minutes gave no events
	10: 37 minutes gave no events
	11: 30 minutes gave no events
22 | HOURS AFFECTED: 16
	2: 10 minutes gave no events
	9: 47 minutes gave no events
	10: 60 minutes gave no events
	11: 60 minutes gave no events
	12: 60 minutes gave no events
	13: 28 minutes gave no events
	14: 47 minutes gave no events
	15: 60 minutes gave no events
	16: 60 minutes gave no events
	17: 60 minutes gave no events
	18: 60 minutes gave no events
	19: 60 minutes gave no events
	20: 60 minutes gave no events
	21: 60 minutes gave no events
	22: 60 minutes gave no events
	23: 13 minutes gave no events
23 | HOURS AFFECTED: 7
	4: 6 minutes gave no events
	5: 10 minutes gave no events
	6: 2 minutes gave no events
	7: 59 minutes gave no events
	8: 60 minutes gave no events
	9: 44 minutes gave no events
	10: 4 minutes gave no events
 ```

**Comment by samjabrahams** [comment]
Latest log info:

```
********** ~ JULY ~ **********
19 | HOURS AFFECTED: 6
	16: 43 minutes gave no events
	17: 60 minutes gave no events
	18: 60 minutes gave no events
	19: 60 minutes gave no events
	20: 60 minutes gave no events
	21: 52 minutes gave no events
20 | HOURS AFFECTED: 1
	4: 10 minutes gave no events
21 | HOURS AFFECTED: 4
	4: 19 minutes gave no events
	5: 5 minutes gave no events
	10: 37 minutes gave no events
	11: 30 minutes gave no events
22 | HOURS AFFECTED: 16
	2: 10 minutes gave no events
	9: 47 minutes gave no events
	10: 60 minutes gave no events
	11: 60 minutes gave no events
	12: 60 minutes gave no events
	13: 28 minutes gave no events
	14: 47 minutes gave no events
	15: 60 minutes gave no events
	16: 60 minutes gave no events
	17: 60 minutes gave no events
	18: 60 minutes gave no events
	19: 60 minutes gave no events
	20: 60 minutes gave no events
	21: 60 minutes gave no events
	22: 60 minutes gave no events
	23: 13 minutes gave no events
23 | HOURS AFFECTED: 9
	4: 6 minutes gave no events
	5: 10 minutes gave no events
	6: 2 minutes gave no events
	7: 59 minutes gave no events
	8: 60 minutes gave no events
	9: 44 minutes gave no events
	10: 4 minutes gave no events
	11: 13 minutes gave no events
	12: 52 minutes gave no events
24 | HOURS AFFECTED: 2
	5: 2 minutes gave no events
	21: 1 minutes gave no events
25 | HOURS AFFECTED: 1
	0: 2 minutes gave no events
26 | HOURS AFFECTED: 3
	7: 18 minutes gave no events
	8: 19 minutes gave no events
	9: 41 minutes gave no events
27 | HOURS AFFECTED: 1
	0: 11 minutes gave no events
28 | HOURS AFFECTED: 1
	0: 7 minutes gave no events
30 | HOURS AFFECTED: 4
	0: 1 minutes gave no events
	5: 7 minutes gave no events
	6: 1 minutes gave no events
	7: 1 minutes gave no events
********** ~ JULY ~ **********
1 | HOURS AFFECTED: 9
	4: 3 minutes gave no events
	6: 8 minutes gave no events
	9: 27 minutes gave no events
	10: 19 minutes gave no events
	11: 6 minutes gave no events
	12: 60 minutes gave no events
	13: 60 minutes gave no events
	14: 40 minutes gave no events
	22: 18 minutes gave no events
2 | HOURS AFFECTED: 6
	0: 4 minutes gave no events
	1: 25 minutes gave no events
	5: 3 minutes gave no events
	6: 6 minutes gave no events
	21: 1 minutes gave no events
	23: 18 minutes gave no events
3 | HOURS AFFECTED: 5
	0: 9 minutes gave no events
	1: 22 minutes gave no events
	4: 7 minutes gave no events
	17: 3 minutes gave no events
	23: 14 minutes gave no events
4 | HOURS AFFECTED: 7
	0: 7 minutes gave no events
	1: 22 minutes gave no events
	2: 6 minutes gave no events
	5: 8 minutes gave no events
	20: 17 minutes gave no events
	21: 60 minutes gave no events
	22: 53 minutes gave no events
5 | HOURS AFFECTED: 8
	3: 10 minutes gave no events
	4: 2 minutes gave no events
	5: 5 minutes gave no events
	8: 50 minutes gave no events
	9: 37 minutes gave no events
	12: 41 minutes gave no events
	13: 60 minutes gave no events
	14: 57 minutes gave no events
6 | HOURS AFFECTED: 1
	4: 8 minutes gave no events
```

**Comment by samjabrahams** [comment]
Looks like my server wasn't seeing any events from the API for the last few hours of July 9th through the first seven hours of July 14th. Anything weird going on those dates? 

Also, how go talks with the manufacturer? Anything you're allowed to mention publicly?

**Comment by samjabrahams** [comment]
I think this issue can be called closed for now! I'm assuming that you guys shut down the server and did some maintenance/modifications from the 9th-14th. Ever since then, it appears that the server is consistently sending out data. Thanks for your diligence, Kegan!
