### ISSUE TITLE
[Enhancement] Aggregate all events for all meters

### ISSUE THREAD

**Issue by kamronbatman** [CityofSantaMonica/Orchard.ParkingData#37]
Currently, the only way to pull the current status (SS/SE) of all meters from scratch is to get all of the meter static data then pull all sensor events going back 3 hours, then on a very liberal interval (2 seconds per request) with retries, request each specific meters sensor event for all meters that were not covered in the 3 hour time span.
Normally this wouldn't be a problem, except the server frequently sends status 500 errors, and simply outright denies the connection.  This means getting something which should be very quick, takes about an hour.

I recommend endpoint:
_/meters/events/all/latest_ or _/meters/events/latest/all_
which returns all meters with their latest sensor event.

**Comment by thekaveman** [comment]
I see your dilemma, but I'm not sure I understand the use-case for obtaining *all* of the latest sensor events all at once. 

These events are coming in at a rate of multiple per second, most of which is just noise (e.g. a car drives over a sensor without ever intending to stop there). By the time you obtained the "latest event" for every single meter, many would likely already be out of date. 

Is there a more focused approach you could take for obtaining events for *specific meters* that you are interested in, at the time you are interested in them?

**Comment by kamronbatman** [comment]
The use for this API is very basic.  Essentially, determining if a meter is available that is close to a person.  Unfortunately, I have been getting 500 errors when querying latest for an individual meter.  In addition to that, the server's response is not reliable, nor quick.  I decided to set up a scraper (which works).  It took a day to get the current SS/SE of all spots and keep my database up to date with the API.

**Comment by thekaveman** [comment]
Right...but as soon as you scraped and populated your database with the "current" events - they were no longer current.

I am able to reproduce the 500 error when querying for latest on an individual meter, so that's something I will certainly look at right away.

**Comment by thekaveman** [comment]
I'm closing this as *not going to implement at this time*.

See #28 we're working on some ideas for making targeted queries easier.
