### ISSUE TITLE
No Events Emitted Since 9/6

### ISSUE THREAD

**Issue by samjabrahams** [CityofSantaMonica/Orchard.ParkingData#40]
I had to step away from my project for a week or so and when I came back, I noticed that my server hadn't received any meter events since "20150906T032706Z", event ordinal 19278480. I cleaned and reset my server to see if it was on my end, and then tried manually sending a GET request to /meters/events, /meters/events/since/(lifetime max), and /meters/events/latest. None of these returned any data.

**Comment by thekaveman** [comment]
Thanks for the report. I have also been away for a few weeks, so trying to catch up on a few things. I will be taking a look at this sooner than later.

**Comment by thekaveman** [comment]
Our meter vendor noticed some errors occurring during that time period. Since I was out of town and unreachable, the vendor decided to just shut down their push service! 

It has since been reactivated, and events are flowing again :relieved:

**Comment by samjabrahams** [comment]
Great- thanks so much for getting this running again. LET THE DATA FLOW! I'll let you know if I see anything weird happen again.
