### ISSUE TITLE
Can't access lots

### ISSUE THREAD

**Issue by tyricec** [CityofSantaMonica/Orchard.ParkingData#42]
The Lots API is responding back with 404 Not Found.

**Comment by thekaveman** [comment]
Thanks for the report, I have confirmed the outage. We're looking in to it.

**Comment by thekaveman** [comment]
It turns out we were having issues with the underlying source system exposed by this API. The issues have been resolved and the `/lots` endpoints are now available. 

Thanks again for the report.

**Comment by tyricec** [comment]
Thanks, appreciate the fix.
