### ISSUE TITLE
Historical parking time data

### ISSUE THREAD

**Issue by danielrjiang** [CityofSantaMonica/Orchard.ParkingData#44]
Hello, is there any available historical parking time data (i.e., a list of entry and exit times for the parking spaces or parking garages)? I was trying to access the sensor events using the API but it seems that this is not available. Thank you for your help.

**Comment by thekaveman** [comment]
Hi there - for historical data on the parking lots/garages, please see this [dataset on our Open Data portal](https://data.smgov.net/Transportation/Parking-Lot-Counts/ng8m-khuz)

Unfortunately the historical data for meters is not available at this time, as this is such a high-volume, more or less "streaming" API. 

May I ask, what are you looking to do with the historical data?

**Comment by danielrjiang** [comment]
Hi, thanks for the reply. Yes, I have downloaded and am looking at the parking lot counts dataset. What I'm looking for is a distribution on how long people typically spend in parking lots, which is a bit different from the dataset you linked. It is for a research project regarding how to control EV charging stations.

**Comment by thekaveman** [comment]
Hi @danielrjiang 

For the lots, we don't have space-specific entry/exit data, just raw counts of available spaces. You could extrapolate from the overall counts of the lots over time, though this is probably less accurate than what you are looking for.
